### ISSUE TITLE
Cookies?

### ISSUE THREAD

**Issue by Rexfelis** [LeastOne/WebBrowserWaiter#1]
This library seems to be working very well for me.  However, I can't seem to figure out how to set cookies.  I'm trying the following:

``` C#
InternetSetCookie("url", "cookie1", "value");
waiter.Await(wb => wb.Navigate(url));
```

Using Fiddler, it doesn't appear that the cookie is being set.  Am I doing something wrong?

**Comment by LeastOne** [comment]
Unfortunately the WebBrowser Contrl doesn't provide a convenient means of manipulating cookies and the WinINet options (i.e. `InternetSetCookie`) are going to be a major pain to work with. Though not ideal I think your best option would be to inject a JavaScript into a loaded page that manipulates the cookie value and then invokes a navigation action. It's important to hand off both the cookie manipulation and the navigation to ensure the cookie gets set before the navigation occurs. If you use JavaScript to set the cookie and then use a separate WebBrowserWaiter action to navigate it could attempt navigation before the JavaScript has been evaluated. I've committed a [unit test in the latest revision](https://github.com/LeastOne/WebBrowserWaiter/commit/f14002db00c69240be2472e5affe77581cbd5e25) which demonstrates how to do this. When running the unit test with Fiddler it shows the cookie value successfully added.

Here's a stripped down example ...

``` C#
waiter.Await(
    p => p.Navigate(url),
    p => {
        var head = p.Document.GetElementsByTagName("head")[0];
        var script = p.Document.CreateElement("script");
        var element = script.DomElement as dynamic;
        element.text =
            @"(function() {{
                document.cookie = 'cookie=value; expires=Tue, 24 Feb 2016 03:59:53 GMT; path=/';
                document.getElementsByTagName('form')[0].submit();
            }})();";
        head.AppendChild(script);
    }
);
```

**Comment by Rexfelis** [comment]
I was able to get InternetSetCookie working, but it took a bit to get it right.  If I end up having problems with it, I'll give your javascript example a try.  Thanks.
