### ISSUE TITLE
Urgent: Problem with loading of Angular Js website 

### ISSUE THREAD

**Issue by jkyadav** [LeastOne/WebBrowserWaiter#10]
I am trying to navigate the website and take screenshot of the loaded page, this seems to be working for static page website but not working for Angular js website.

In the case of angular js it only loads the static page.

Can you please help me with this, I need to use your WebBrowserWaiter in loop.
Frustrated with WebBrowser not getting exact idea.
here is my code.

```
List<string> lststrWebSites = new List<string>();
            lststrWebSites.Add("angularjs webside");
            lststrWebSites.Add("angularjs webside");
            foreach (string strWebSite in lststrWebSites)
            {
                using (var waiter = new wb.WebBrowserWaiter())
                {
                    waiter.Await(
                        TimeSpan.FromSeconds(40),
                        // NOTE: wb is an instance of System.Windows.Forms.WebBrowser
                        wbc => wbc.Navigate(strWebSite),
                        wb =>
                        {
                            //if (wb.DocumentText.Contains("Seller:"))
                            //{
                            string fileName = Path.GetFullPath(
                                "screenshot_" + DateTime.Now.Ticks + ".png");
                            int width = wb.Width;
                            //int height = this.webBrowser1.Height;
                            int height = 1200;
                            using (Graphics graphics = wb.CreateGraphics())
                            using (Bitmap bitmap = new Bitmap(width, height, graphics))
                            {
                                Rectangle bounds = new Rectangle(0, 100, width, height);
                                wb.DrawToBitmap(bitmap, bounds);
                                bitmap.Save(Path.GetFullPath(fileName), ImageFormat.Png);
                            }
                            //}
                        }
                    );
                }
            }
```

**Comment by LeastOne** [comment]
The WebBrowser control uses the version of Internet Explorer installed,
what version do you have installed? Have you tested your version of
Internet Explorer with the specific AngularJS website? Is there a publicly
available Angular JS website that you've tested your code with that does
not work that I could test against? I'd come up with one now but it's 1:00
AM local and I'm heading to bed.

**Comment by jkyadav** [comment]
You can try this website as sample https://www.copart.com/lot/32063616/?resultIndex=110&totalRecords=520&backTo=%2Fsearch%2Frunanddrive%2F%3FdisplayStr%3DRun%20and%20Drive&from=%2FvehicleFinder&displayStr=Search%20Results%20for:%20Run%20and%20Drive&viewedLot=32063616

**Comment by LeastOne** [comment]
I was able to to use your code to produce the attached image. Can you provide more specifics concerning the exact problem you are experiencing?
![screenshot_636132550885365298](https://cloud.githubusercontent.com/assets/5291141/19816244/2e101db8-9d0c-11e6-9f8b-1f3c189231fc.png)

**Comment by jkyadav** [comment]
Can you please attach your complete code here if possible.

**Comment by LeastOne** [comment]
You already have it. I used your exact code. There were only two changes I made.

First I replaced this ...

```
lststrWebSites.Add("angularjs webside");
lststrWebSites.Add("angularjs webside");
```

With this per the URL you provided ...

```
lststrWebSites.Add("https://www.copart.com/lot/32063616/?resultIndex=110&totalRecords=520&backTo=%2Fsearch%2Frunanddrive%2F%3FdisplayStr%3DRun%20and%20Drive&from=%2FvehicleFinder&displayStr=Search%20Results%20for:%20Run%20and%20Drive&viewedLot=32063616");
```

Second I changed the following which prevented the code from compiling ...

```
using (var waiter = new wb.WebBrowserWaiter())
```

To this ...

```
using (var waiter = new WebBrowserWaiter())
```
