### ISSUE TITLE
Specified cast is invalid on Window.Frames

### ISSUE THREAD

**Issue by Rexfelis** [LeastOne/WebBrowserWaiter#4]
I have the following code:

``` C#
waiter.Await(wb => wb.Navigate(url), wb => wb.Document.Window.Error += (q, r) => r.Handled = true);
Thread.Sleep(250);
HtmlWindowCollection frames = waiter.Await(wb => wb.Document.Window.Frames);
string result = frames[0].Document.Body.OuterHtml;
```

I'm getting a "Specified cast is invalid" when executing the bottom line.

**Comment by Rexfelis** [comment]
Ah apparently it is a threading issue similar to the instruction of not extracting the WebBrowser.  I had to change it to the following:

```
waiter.Await(wb => result = wb.Document.Window.Frames[0].Document.Body.OuterHtml);
```

**Comment by LeastOne** [comment]
That makes sense. Essentially any action outside of an `Await` that causes an invocation of something within WebBrowser is like to have unexpected consequences. In this particular situation I suspect that accessing `Document` required the WebBrowser to do more than just return a reference.
