### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by tonyhallett** [LeastOne/WebBrowserWaiter#6]
The behavior that I am getting is:
Navigate first url
Second action is called after navigation ( add script to the page, invoke it )
Navigate second url
Second action is called BUT THE DOCUMENT IS THAT FOR THE FIRST URL.

What am I doing wrong ?

Thanks Tony
( Code below )

```
    public List<string> GetDownloadUrls(List<string> bookmarkUrls)
    {
        var actions = GetActions(bookmarkUrls);
        WebBrowserWaiter.WebBrowserWaiter waiter = new WebBrowserWaiter.WebBrowserWaiter();

        foreach (var a in actions)
        {
            waiter.Await(a);
        }
        waiter.Dispose();
        return downloadUrls;
    }

    private Action<WebBrowser>[][] GetActions(List<string> bookmarkUrls)
    {
        return bookmarkUrls.Select(url =>
        {
            var navigate = new Action<WebBrowser>(wb =>
            {
                wb.ScriptErrorsSuppressed = true;
                wb.Navigate(url);
            });
            return new Action<WebBrowser>[] { navigate, AddScriptAndGetDownloadUrl };
        }).ToArray();
    }
```

**Comment by LeastOne** [comment]
I'm having trouble reconciling your description of the problem with the code you provided. Could you please try to add more details about what your are trying to accomplish and what is not working correctly?

Especially could you include the `AddScriptAndGetDownloadUrl` code?
