### ISSUE TITLE
Its no work correctly work 

### ISSUE THREAD

**Issue by Radzhab** [LeastOne/WebBrowserWaiter#7]
```
public async void Axixa()
{
    using (var waiter = new WebBrowserWaiter.WebBrowserWaiter())
    {
        waiter.Await(
            // NOTE: wb is an instance of System.Windows.Forms.WebBrowser
            wb => wb.Navigate("https://www.google.com/search?q=pi"));
    }
}
```

When i clear `waiter.Await()` its work correctly. What i make wrong?

**Comment by LeastOne** [comment]
Can you please provide more detail? What do you mean by "clear"? Can you describe what is wrong? Is it not behaving as you expect? Is there an exception being thrown? Are you experiencing some other form of error?

**Comment by Radzhab** [comment]
```
public async void Axixa()
{
    using (var waiter = new WebBrowserWaiter.WebBrowserWaiter())
    {
            wb => wb.Navigate("https://www.google.com/search?q=pi");
    }
}
```

`
its work.

but this code not work. No errors, no exceptions

```
public async void Axixa()
{
    using (var waiter = new WebBrowserWaiter.WebBrowserWaiter())
    {
        waiter.Await(
            // NOTE: wb is an instance of System.Windows.Forms.WebBrowser
            wb => wb.Navigate("https://www.google.com/search?q=pi"));
    }
}
```

**Comment by LeastOne** [comment]
You say the first example works but as it is written it cannot compile because it contains an invalid lambda expression. Can you correct the examples so they compile or provide new examples?
