### ISSUE TITLE
Problem running on Azure

### ISSUE THREAD

**Issue by rickduarte** [LeastOne/WebBrowserWaiter#9]
I have a project running fine on my local machine.
When I try to run on Azure it throws an Exception:

> An exception of type 'System.Runtime.InteropServices.COMException' occurred in System.Windows.Forms.dll but was not handled in user code
> 
> Additional information: Error HRESULT E_FAIL has been returned from a call to a COM component.

**Comment by rickduarte** [comment]
If it helps, the error occurs always when I try to navigate:
`waiter.Await(wb=>wb.Navigate("http://consultas.detrannet.sc.gov.br/servicos/consultaveiculo.asp"));`

**Comment by LeastOne** [comment]
Are you attempting to use WebBrowserWaiter in an Azure Web App, Cloud Service (or similar)?  If so, I highly doubt it will work since it requires Internet Explorer, which I assume does not exist for most Azure offerings. The only Azure service I've ever used WebBrowserWaiter in is an Azure Virtual Machine.

**Comment by rickduarte** [comment]
Hmmmm...
I'm using a Web App.
Do you know if there's a way to make it work or some alternatives?

**Comment by DreamOnTheGo** [comment]
can you update the code which surport the webbrowser being  waiting  unitil some element appears in the page ( I'd like you use the  delegate)and Set a timeout property  thank u very much

**Comment by LeastOne** [comment]
@DreamOnTheGo, your comment seems off topic I'd recommend creating a separate thread if you still have a question / feature request.

**Comment by LeastOne** [comment]
@rickduarte, sorry for the long overdue reply, you've likely moved on, however, for anyone else coming after this I'll update the thread with a response.

By far the best alternative in my experience is [Selenium](http://www.seleniumhq.org/). Actually, its my preferred choice over WebBrowserWaiter as its truly designed for browser automation unlike WebBrowser + WebBrowserWaitier which is really just a poor mans implementation for scenarios in which your limited to those options.

However, in your particular situation I doubt if you'll be able to find any suitable browser automation that will run in an Azure Web App container. Reason being that most browser automation tools rely on an underlying graphics device interface (GDI) that is typically restricted or non-existent in an application container such as an Azure Web App

As far as I'm aware your most practical option would be to use a virtual machine on Azure.
